[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moq"
version = "0.1.0"
description = "Python implementation of draft-ietf-moq-transport-17"
readme = "API.md"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["moq*"]

[tool.setuptools]
include-package-data = true
