network:
  network_ip: 127.0.0.1
  acn_agent_port: 9010
  arf_port: 9001
  agent_gw_ws_port: 9002
  agent_gw_moq_port: 9003
  web_ui_port: 9004
  path: /ws
storage:
  identity_file: data/identity.json
  private_key_file: data/keys/private_key.pem
  public_key_file: data/keys/public_key.pem
  log_dir: logs
log_level: INFO
